version: '3.7'

services:
  gtw:
    image: nginx:1.17.0
    depends_on:
      - api
    volumes:
      - ./gtw/nginx.conf:/etc/nginx/nginx.conf
      - ./gtw/server.crt:/etc/nginx/server.crt
      - ./gtw/server.key:/etc/nginx/server.key
    ports:
      - 80:80
      - 443:443
    networks:
      default:
        aliases:
          - api.dev.etc.com.mx
  api:
    image: forg-node-yarn
    build:
      context: .
      dockerfile: dockerfiles/yarn/yarn.Dockerfile
    environment:
      #DEV-DB-LOCAL
      AWS_ACCESS_KEY_ID: xxxx
      AWS_SECRET_ACCESS_KEY: xxxx
      AWS_COGNITO_USER_SECRET: xxxx
      AWS_COGNITO_USER_ACCESS_KEY: xxxx 
      AWS_COGNITO_USERPOOLID: xxxx
      AWS_COGNITO_REGION: xxxx
      PORT: 8080
      NODE_ENV: development
    volumes:
      - ./etc-api:/app
      - api-node_modules:/app/node_modules/
    command: sh -c 'echo "Running install ..."'
      #&& yarn install
      #&& echo "Running migration..."
      #&& echo "Running ..."
      #&& yarn run dev'

  toll1:
    image: forg-node-yarn
    volumes:
      - ./etc-client:/opt
    command: sh -c " echo 'OPE OWNER OF TOLL ...'
       && sleep infinity"
        #command: >
      #bash -c " echo 'OPE OWNER OF TOLL ...'"
      #&& cd /var/src/rabbitmq
      #&& while true;do python3 send.py;done"

  toll2:
    image: forg-node-yarn
    volumes:
      - ./etc-client:/opt
    command: sh -c " echo 'OPE OWNER OF TOLL ...'
       && sleep infinity"
        #command: >
      #bash -c " echo 'OPE OWNER OF TOLL ...'"
      #&& cd /var/src/rabbitmq
      #&& while true;do python3 send.py;done"

  toll3:
    image: forg-node-yarn
    volumes:
      - ./etc-client:/opt
    command: sh -c " echo 'OPE OWNER OF TOLL ...'
       && sleep infinity"
        #command: >
      #bash -c " echo 'OPE OWNER OF TOLL ...'"
      #&& cd /var/src/rabbitmq
      #&& while true;do python3 send.py;done"

  toll4:
    image: forg-node-yarn
    volumes:
      - ./etc-client:/opt
    command: sh -c " echo 'OPE OWNER OF TOLL ...'
       && sleep infinity"
        #command: >
      #bash -c " echo 'OPE OWNER OF TOLL ...'"
      #&& cd /var/src/rabbitmq
      #&& while true;do python3 send.py;done"

  #will check if adminer should be necesary to dbsu, although I think it should not.

volumes:
  api-node_modules:
